### PR TITLE
[MKW] Display the current status of the "Open Host" feature

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mkwcat** [comment]
In what case is the instruction text message actually displayed?

**Comment by ghost** [comment]
> In what case is the instruction text message actually displayed?

When the "Friends" button is clicked on the WiFi menu page.

**Comment by mkwcat** [comment]
How long does it show, and does it obscure base game text at all?

**Comment by ghost** [comment]
> How long does it show, and does it obscure base game text at all?

The custom message will remain displayed until another button is selected. After that point, no changes are made to the messages.

**Comment by ghost** [comment]
Closing this pull request as it was determined to be unnecessary.

**Pull request closed without merging**
