### PR TITLE
Github Actions Workflow

### PR DESCRIPTION
**Pull request by lilousky**
Addresses #3, as well as fixes an include path which caused building to fail on linux filesystems

### CODE REVIEW

**Comment by mkwcat** [comment]
The dev private key should be called `private-key.pem` in the package rather than `private-key-dev.pem`, because that's what the server expects

**Comment by mkwcat** [comment]
Looks good now, but I have a suggestion to have it also upload the unstripped build `.elf` files for the payloads, which contain information that would be helpful for debugging. Not part of the Package artifact but separate or part of the Payloads artifact would be nice

**Comment by noahpistilli** [comment]
Could you also squash your last two commits?

**Comment by lilousky** [comment]
> Could you also squash your last two commits?

Done

**Comment by lilousky** [comment]
> Looks good now, but I have a suggestion to have it also upload the unstripped build `.elf` files for the payloads, which contain information that would be helpful for debugging. Not part of the Package artifact but separate or part of the Payloads artifact would be nice

Should the elfs only be uploaded in the dev build or in both dev and prod

**Comment by mkwcat** [comment]
Both

**Comment by lilousky** [comment]
The workflow now uploads the `.elf` files onto the action tab.

**Comment by lilousky** [comment]
I've gone ahead and squashed that into the other actions commits

**Comment by mkwcat** [comment]
Thank you, looks good to me now

**Pull request merged**
